# TODO think about adding page size (pagination)
# TODO think about adding root path for URL


# where the audio files are stored, locally
audioDirectory: "g:/Users/phllp/go/github.com/phllpmcphrsn/voice-uploader/audio_files"

api:
  path: "/voice-quips"
  address: ":9090"
  env: "dev"

log:
  level: debug

database:
  file:
    host: "localhost"
    port: 5432
    name: "voice_quips"
    ssl:
      enabled: false
    credentials:
      envvar: true  # enable obtaining credentials from envvars
      userVar: "POSTGRES_USER"
      passwordVar: "POSTGRES_PASSWORD"
  s3:
    # path:
    #   config: "g:/Users/phllp/go/github.com/phllpmcphrsn/voice-uploader/.aws/config"
    #   credentials: "g:/Users/phllp/go/github.com/phllpmcphrsn/voice-uploader/.aws/credentials"
    bucket: "quips"
    credentials:
      envvar: true
      userVar: "MINIO_USER"
      passwordVar: "MINIO_PASS"
    endpoint: "localhost:9090"
    region: "us-east-1"
    ssl:
      enabled: false
    retry: 1
    timeout: 100 # ms